- name: Append line to file
  copy:
    dest: /home/ubuntu/ansible/roles/start-monitoring/hi.txt
    content: "{{ lookup('file', '/home/ubuntu/ansible/roles/start-monitoring/hi.txt') }}\nI'm sending requests"

- name: Send GET request to backend server
  uri:
    url: http://172.26.134.134:5000/status
    # url: 'http://{{ ansible_default_ipv4.address }}:5000/status'
    method: GET
    return_content: yes
  register: results

- name: Append line to file
  copy:
    dest: /home/ubuntu/ansible/roles/start-monitoring/hi.txt
    content: "{{ lookup('file', '/home/ubuntu/ansible/roles/start-monitoring/hi.txt') }}\n{{results.json}}   "

- name: Scaling up
  delegate_to: twitter
  script: ../deploy-backend/deploy-backend.sh
  register: outScalingUP
  when: results.json.status == true
  ignore_errors: true
- debug: var=outScalingUP.stdout_lines

- name: Scaling down
  delegate_to: twitter
  script: ../remove-backend/remove-backend.sh
  register: outScalingDown
  when: results.json.status == false
  ignore_errors: true
- debug: var=outScalingDown.stdout_lines