- name: Append Line To File
  copy:
    dest: /home/ubuntu/ansible/roles/start-monitoring/monitoring-result.txt
    content: "{{ lookup('file', '/home/ubuntu/ansible/roles/start-monitoring/monitoring-result.txt') }}\nI'm sending requests"

- name: Send GET Request To Backend Server
  uri:
    url: http://172.26.134.134:5000/status
    method: GET
    return_content: yes
  register: results

- name: Append Line To File
  copy:
    dest: /home/ubuntu/ansible/roles/start-monitoring/monitoring-result.txt
    content: "{{ lookup('file', '/home/ubuntu/ansible/roles/start-monitoring/monitoring-result.txt') }}\n{{results.json}}   "

- name: Scaling Up
  delegate_to: twitter
  script: ../deploy-backend/deploy-backend.sh
  register: outScalingUP
  when: results.json.status == true
  ignore_errors: true
- debug: var=outScalingUP.stdout_lines

- name: Scaling Down
  delegate_to: twitter
  script: ../remove-backend/remove-backend.sh
  register: outScalingDown
  when: results.json.status == false
  ignore_errors: true
- debug: var=outScalingDown.stdout_lines