---
# # Attach volumes to every vm
# - hosts: all
#   roles:
#     - role: volume-setup

# Remove couchdb setting
# - hosts: database
#   roles:
#     - role: couchdb-remove
#   ignore_errors: true

# # Preparing couchdb container
# - hosts: database
#   roles:
#     - role: couchdb-setup

# # Set up each couchdb cluster
# - hosts: couchdb
#   roles:
#     - role: cluster-setup

# # Deploy mastodon harvester
# - hosts: mastodon
#   roles:
#     - role: deploy-mastodon-harvester

# # Deploy twitter harvester
# - hosts: twitter
#   roles:
#     - role: deploy-twitter-harvester

# Deploy web server for backend
# - hosts: twitter
#   roles:
#     - role: deploy-backend

# Deploy web server for frontend
- hosts: web
  roles:
    - role: deploy-frontend

# # Start monitoring
# - hosts: mastodon
#   roles:
#     - role: start-monitoring